svirt: Add (again) root-sut-serial console
Fixes: poo#51725, poo#45863

Depends on changes in os-autoinst:
https://github.com/os-autoinst/os-autoinst/pull/1109

ATM serial console is added only for s390x (not for other svirt users,
e.g. Hyper-V, VMware and any other).

Also use svirt constants for devices and ports instead of hardwired values.

NOTE: this is fixed commit ea71a239e ("svirt: Add root-sut-serial console")

CHANGELOG from ea71a239e:
use backend::svirt->add_pty() (instead of backend::svirt->add_serial_console())
and pass target_type => 'virtio'. The reason is that libvirt 4.0 (from
SLE12 SP4, SLE15 GA) uses default console type on s390x, which is sclp),
which leads to error during virsh define /var/lib/libvirt/images/openQA-SUT-1.xml:
error: Failed to define domain from /var/lib/libvirt/images/openQA-SUT-1.xml
error: unsupported configuration: Only the first console can be a serial port

Older version from SLE12 SP3 (libvirt 3.3) is ok with the default,
that's why it wasn't discovered before.